package com.labbaslabs.jampsfit.database

import org.json.JSONObject

private fun JSONObject.putNullable(key: String, value: Int?): JSONObject = if (value == null) put(key, JSONObject.NULL) else put(key, value)
private fun JSONObject.intOrNull(key: String): Int? = if (isNull(key)) null else optInt(key)

fun HealthEntry.toJson() = JSONObject().put("timestamp", timestamp).putNullable("battery", battery).putNullable("heartRate", heartRate).putNullable("spo2", spo2).putNullable("systolic", systolic).putNullable("diastolic", diastolic).putNullable("steps", steps).putNullable("activityCount", activityCount).putNullable("distance", distance).putNullable("calories", calories).putNullable("sleepMinutes", sleepMinutes).putNullable("deepSleepMinutes", deepSleepMinutes).putNullable("lightSleepMinutes", lightSleepMinutes).put("sleepSegmentsJson", sleepSegmentsJson)
fun JSONObject.toHealthEntry() = HealthEntry(timestamp = optLong("timestamp"), battery = intOrNull("battery"), heartRate = intOrNull("heartRate"), spo2 = intOrNull("spo2"), systolic = intOrNull("systolic"), diastolic = intOrNull("diastolic"), steps = intOrNull("steps"), activityCount = intOrNull("activityCount"), distance = intOrNull("distance"), calories = intOrNull("calories"), sleepMinutes = intOrNull("sleepMinutes"), deepSleepMinutes = intOrNull("deepSleepMinutes"), lightSleepMinutes = intOrNull("lightSleepMinutes"), sleepSegmentsJson = optString("sleepSegmentsJson").takeIf { it != "null" })

fun FoodEntity.toJson() = JSONObject().put("name", name).put("source", source).put("role", role).put("unitLabel", unitLabel).put("kcalPerUnit", kcalPerUnit).put("defaultAmount", defaultAmount).put("stepSize", stepSize).put("enabled", enabled).put("availableAmount", availableAmount).put("isCustom", isCustom).put("onShoppingList", onShoppingList)
fun JSONObject.toFood() = FoodEntity(name = optString("name"), source = optString("source"), role = optString("role"), unitLabel = optString("unitLabel"), kcalPerUnit = optInt("kcalPerUnit"), defaultAmount = optDouble("defaultAmount").toFloat(), stepSize = optDouble("stepSize").toFloat(), enabled = optBoolean("enabled", true), availableAmount = if (isNull("availableAmount")) null else optDouble("availableAmount").toFloat(), isCustom = optBoolean("isCustom"), onShoppingList = optBoolean("onShoppingList"))

fun FestivalEntity.toJson() = JSONObject().put("name", name).put("imageUri", imageUri).put("isActive", isActive).put("createdAt", createdAt).put("updatedAt", updatedAt)
fun JSONObject.toFestival() = FestivalEntity(name = optString("name", DEFAULT_FESTIVAL_NAME), imageUri = optString("imageUri").takeIf { it != "null" }, isActive = optBoolean("isActive"), createdAt = optLong("createdAt"), updatedAt = optLong("updatedAt"))

fun EventEntity.toJson() = JSONObject().put("festivalId", festivalId).put("type", type).put("name", name).put("startTime", startTime).put("endTime", endTime).put("startSteps", startSteps).put("startActivityCount", startActivityCount).put("startDistance", startDistance).put("startCalories", startCalories).put("durationSeconds", durationSeconds).put("stepDelta", stepDelta).put("activityDelta", activityDelta).put("distanceDelta", distanceDelta).put("calorieDelta", calorieDelta).put("heartRateSamples", heartRateSamples).put("averageBpm", averageBpm).put("minBpm", minBpm).put("maxBpm", maxBpm).put("estimatedWorkoutCalories", estimatedWorkoutCalories).put("lastUpdatedTime", lastUpdatedTime)
fun JSONObject.toEvent() = EventEntity(festivalId = if (isNull("festivalId")) null else optLong("festivalId"), type = optString("type", EVENT_TYPE_DANCING), name = optString("name", DEFAULT_DANCING_EVENT_NAME), startTime = optLong("startTime"), endTime = if (isNull("endTime")) null else optLong("endTime"), startSteps = intOrNull("startSteps"), startActivityCount = intOrNull("startActivityCount"), startDistance = intOrNull("startDistance"), startCalories = intOrNull("startCalories"), durationSeconds = optInt("durationSeconds"), stepDelta = optInt("stepDelta"), activityDelta = optInt("activityDelta"), distanceDelta = optInt("distanceDelta"), calorieDelta = optInt("calorieDelta"), heartRateSamples = optInt("heartRateSamples"), averageBpm = intOrNull("averageBpm"), minBpm = intOrNull("minBpm"), maxBpm = intOrNull("maxBpm"), estimatedWorkoutCalories = optInt("estimatedWorkoutCalories"), lastUpdatedTime = optLong("lastUpdatedTime"))

fun MealEntity.toJson() = JSONObject().put("festivalId", festivalId).put("name", name).put("type", type).put("calories", calories).put("details", details).put("createdAt", createdAt)
fun JSONObject.toMeal() = MealEntity(festivalId = if (isNull("festivalId")) null else optLong("festivalId"), name = optString("name", "Meal"), type = optString("type", "Meal"), calories = optInt("calories"), details = optString("details"), createdAt = optLong("createdAt"))
fun CandyEntity.toJson() = JSONObject().put("festivalId", festivalId).put("name", name).put("startTime", startTime).put("endTime", endTime).put("size", size).put("createdAt", createdAt)
fun JSONObject.toCandy() = CandyEntity(festivalId = if (isNull("festivalId")) null else optLong("festivalId"), name = optString("name", "Candy"), startTime = optLong("startTime"), endTime = optLong("endTime"), size = optInt("size"), createdAt = optLong("createdAt"))
fun SupplementEntity.toJson() = JSONObject().put("name", name).put("dailyTargetMg", dailyTargetMg).put("singleDoseMg", singleDoseMg).put("selectedAmountMg", selectedAmountMg).put("stepMg", stepMg).put("maxDailyMg", maxDailyMg).put("sortOrder", sortOrder).put("rampEnabled", rampEnabled).put("rampStartMg", rampStartMg).put("rampTargetMg", rampTargetMg).put("rampDays", rampDays).put("rampStartedAt", rampStartedAt).put("updatedAt", updatedAt)
fun JSONObject.toSupplement() = SupplementEntity(name = optString("name", "Supplement"), dailyTargetMg = optInt("dailyTargetMg", 100), singleDoseMg = optInt("singleDoseMg", 100), selectedAmountMg = optInt("selectedAmountMg", 100), stepMg = optInt("stepMg", 100), maxDailyMg = optInt("maxDailyMg", 100), sortOrder = optInt("sortOrder"), rampEnabled = optBoolean("rampEnabled"), rampStartMg = optInt("rampStartMg", 100), rampTargetMg = optInt("rampTargetMg", 100), rampDays = optInt("rampDays"), rampStartedAt = if (isNull("rampStartedAt")) null else optLong("rampStartedAt"), updatedAt = optLong("updatedAt"))
